version: "3.3"
services:
  webserver:
    container_name: 'webserver'
    image: tomcat
    networks:
      - innerNet

  mitm:
    container_name: 'mitm'
    build: .
    stdin_open: true
    tty: true
    networks:
      - innerNet

  victim:
    container_name: 'victim'
    image: busybox
    stdin_open: true
    tty: true
    networks:
      - innerNet

networks:
  innerNet:
    driver: bridge